version: 0.0
os: linux
files:
  - source: https://github.com/nadzhafov20/ITRole-Back.git
    destination: /myroletest
hooks:
  BeforeInstall:
    - location: /myroletest/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /myroletests/cripts/configure_database.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /myroletest/scripts/start_server.sh
      timeout: 300
      runas: root
