version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py runserver
artifacts:
  files:
    - '**/*'